### ISSUE TITLE
'LabelMaker' object has no attribute 'set_mode'

### ISSUE THREAD

**Issue by tarosk** [piksel/pytouch-cube#6]
Print failed with"
2021-02-22T13:32:41.145998 Starting print thread...
2021-02-22T13:32:41.175001 Building bit map from image...
2021-02-22T13:32:41.175998 Printing label, width: 126 height: 68
2021-02-22T13:32:41.175998 Opening serial device connection...
2021-02-22T13:32:42.477811 Using serial device: COM3
2021-02-22T13:32:42.478817 Failed to print due to the following error:
'LabelMaker' object has no attribute 'set_mode'

Console output:
C:\Temp\pytouch-cube>gui.py
PIL not found. Image output disabled.

####################### CREATING EMPTY ######################
COM3
COM4
Add, class: <class 'printables.text.Text'> parent: <__main__.PyTouchCubeGUI object at 0x0000029A56C5D550>
Default font: Helvetica Neue [] Helvetica Neue,8,-1,0,50,0,0,0,0,0
0 Helvetica Neue,-1,68,0,50,0,0,0,0,0
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setFont: Painter not active
QPainter::end: Painter not active, aborted
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::end: Painter not active, aborted
43 Arial,-1,68,0,50,0,0,0,0,0 T
73 Arial,-1,68,0,50,0,0,0,0,0 Te
107 Arial,-1,68,0,50,0,0,0,0,0 Tes
126 Arial,-1,68,0,50,0,0,0,0,0 Test
QLayout: Attempting to add QLayout "" to PyTouchCubeGUI "", which already has a layout
C:\Temp\pytouch-cube\gui.py:412: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  modal.setFixedWidth(self.width() * .9)
C:\Temp\pytouch-cube\gui.py:413: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  modal.setFixedHeight(self.height()*.9)
wat2
Input: 0
Output: 0
wat4

**Comment by piksel** [comment]
Probably missed it when doing a partial commit.
Should be fixed now.
