### ISSUE TITLE
Suggestion: resize label preview with window

### ISSUE THREAD

**Issue by tarosk** [piksel/pytouch-cube#8]
resize label preview with window, so that longer labels can be previewed without scroll bar. If scroll bar is visible, resize preview verticaly, so that scroll bar does not overlap preview.

**Comment by piksel** [comment]
Yeah, I noticed that as well. Doing a large refactor/rebuild of the code base right now where it has been fixed.

**Comment by piksel** [comment]
Still some cleanup left, but it mostly works now:
![image](https://user-images.githubusercontent.com/807383/109332904-0bcad300-785f-11eb-8663-01416b01a491.png)
